build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.21
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
test_binary_build_commands: |
  ./hack/install-lint.sh
tests:
- as: lintcheck
  commands: make lintCheck
  container:
    from: src
zz_generated_metadata:
  branch: main
  org: openshift-kni
  repo: telco-reference
